daylogapp/api/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('static.urls')),
    url(r'^daylog/', include('daylog.urls')),
]

daylogapp/daylog/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'daylog'
urlpatterns = [
    url(r'^$', views.get_list, name='get_list'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<slug>.+)/delete$', views.delete, name='delete'),
    url(r'^(?P<slug>.+)/edit$', views.edit, name='edit'),
    url(r'^(?P<slug>.+)/$', views.details, name='details'),
]

daylogapp/daylog/models.py
from django.db import models

class Daylog(models.Model):
    CATEGORY_ADEQUATE = "Adequate"
    CATEGORY_MINOR = "Minor"
    CATEGORY_MAJOR = "Major"
    CATEGORY_CHOICES = (
        (CATEGORY_ADEQUATE, CATEGORY_ADEQUATE),
        (CATEGORY_MINOR, CATEGORY_MINOR),
        (CATEGORY_MAJOR, CATEGORY_MAJOR),
    )

    title = models.CharField(max_length=255, blank=False)
    slug = models.CharField(max_length=50, blank=False, unique=True)
    location = models.CharField(max_length=100, blank=False)
    log_at = models.DateField(blank=False, unique=True)
    category = models.CharField(max_length=25, choices=CATEGORY_CHOICES, blank=False)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s: %s" % (self.log_at, self.title)

daylogapp/daylog/forms.py
from django import forms

from .models import Daylog

class DaylogForm(forms.ModelForm):
    class Meta:
        model = Daylog
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        self.operation = kwargs.pop('operation', None)
        super(DaylogForm, self).__init__(*args, **kwargs)

    def full_clean(self):
        super(DaylogForm, self).full_clean()

        if self.operation == 'edit':
            if 'slug' in self._errors:
                del self._errors['slug']
            if 'log_at' in self._errors:
                del self._errors['log_at']

        return self.cleaned_data

daylogapp/daylog/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render

from .models import Daylog
from .forms import DaylogForm

# TODO: Add proper loggers

def get_list(request):
    daylogs = Daylog.objects.all()
    return render(request, 'daylog/index.html', { 'daylogs': daylogs })

def details(request, slug):
    try:
        daylog = Daylog.objects.get(slug = slug)
    except Daylog.DoesNotExist:
        # TODO: Put error message in a constant file, maybe in model?
        messages.error(request, "Day Log does not exist.", "danger")
        return get_list(request)

    return render(request, 'daylog/form.html', {
        'daylog': daylog,
        'operation': 'view'
    })

def create(request):
    if request.method == 'POST':
        # TODO: Add user-daylog authentication mmodified_atdleware
        daylog_form = DaylogForm(request.POST)
        if daylog_form.is_valid():
            daylog_form.save()
            messages.info(request, "Day Log created.", "info")
            return redirect('daylog:get_list')
        else:
            return render(request, 'daylog/form.html', {
                'daylog': request.POST,
                'errors': daylog_form.errors
             })

    return render(request, 'daylog/form.html', {
        'action': 'daylog:create',
        'operation': 'create',
    })

def delete(request, slug):
    # TODO: Add user-daylog authentication middleware
    try:
        daylog = Daylog.objects.get(slug = slug)
    except Daylog.DoesNotExist:
        messages.error(request, "Day Log does not exist.", "danger")
        return redirect('daylog:get_list')

    daylog.delete()
    messages.error(request, "Day Log deleted.", "info")
    return redirect('daylog:get_list')

def edit(request, slug):
    try:
        old_daylog = Daylog.objects.get(slug = slug)

        if request.method == 'POST':
            # TODO: Add user-daylog authentication middleware
            daylog_form = DaylogForm(request.POST, operation='edit')
            if daylog_form.is_valid():
                new_daylog = daylog_form.instance
                new_daylog.id = old_daylog.id
                new_daylog.created_at = old_daylog.created_at
                new_daylog.modified_at = old_daylog.modified_at
                new_daylog.save()
                messages.info(request, "Day Log edited.", "info")
                return redirect('daylog:get_list')
            else:
                return render(request, 'daylog/form.html', {
                    'daylog': request.POST,
                    'action': 'daylog:edit',
                    'operation': 'edit',
                    'errors': daylog_form.errors
                 })
    except Daylog.DoesNotExist:
        messages.error(request, "Day Log does not exist.", "danger")
        return redirect('daylog:get_list')

    return render(request, 'daylog/form.html', {
        'daylog': old_daylog,
        'action': 'daylog:edit',
        'operation': 'edit',
    })

daylogapp/daylog/templates/daylog/form.html
{% extends 'base.html' %}

{% block content %}
<div class="card">
    <h3 class="card-header">{{ operation | capfirst }} Day Log</h3>

    <div class="card-block">

        <form action="{% if action %}{% if operation == 'edit' %}{% url action daylog.slug %}
            {% else %}{% url action %}{% endif %}{% endif %}" method="post"
            enctype="application/x-www-form-urlencoded">
            {% csrf_token %}

            {% if operation == 'edit' %}
                <input type="hidden" value="PUT" name="_method">
            {% endif %}

            <div class="container">
                <div class="form-group row">
                    <label for="title" class="col-sm-2 col-form-label text-right">Title</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" id="title" name="title"
                            placeholder="Describe your log" required
                            {% if operation == 'view' %}readonly{% endif %}
                            >{% if daylog %}{{ daylog.title }}{% endif %}</textarea>
                        {% if errors.title %}
                            {% include "alert.html" with type='danger' message=errors.title %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="slug" class="col-sm-2 col-form-label text-right">Slug</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="slug" name="slug"
                            placeholder="example-daylog-slug" required
                            {% if operation == 'view' or operation == 'edit' %}readonly{% endif %}
                            value="{% if daylog %}{{ daylog.slug }}{% endif %}">
                        {% if errors.slug %}
                            {% include "alert.html" with type='danger' message=errors.slug %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="location" class="col-sm-2 col-form-label text-right">Location</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="location" name="location"
                            placeholder="Location of log" required
                            {% if operation == 'view' %}readonly{% endif %}
                            value="{% if daylog %}{{ daylog.location }}{% endif %}">
                        {% if errors.location %}
                            {% include "alert.html" with type='danger' message=errors.location %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <label for="log_at" class="col-sm-2 col-form-label text-right">Date of log</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" id="log_at" name="log_at"
                            placeholder="Date of log" required
                            {% if operation == 'view' or operation == 'edit' %}readonly{% endif %}
                            value="{% if daylog %}{{ daylog.log_at }}{% endif %}">
                        {% if errors.log_at %}
                            {% include "alert.html" with type='danger' message=errors.log_at %}
                        {% endif %}
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label text-right">Category</label>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio"
                                    name="category" id="category" value="Adequate" required
                                    {% if operation == 'view' %}disabled{% endif %}
                                    {% if daylog and daylog.category == "Adequate" %}checked{% endif %}>
                                Adequate
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio"
                                    name="category" id="category" value="Minor" required
                                    {% if operation == 'view' %}disabled{% endif %}
                                    {% if daylog and daylog.category == "Minor" %}checked{% endif %}>
                                Minor
                            </label>
                        </div>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" type="radio"
                                    name="category" id="category" value="Major" required
                                    {% if operation == 'view' %}disabled{% endif %}
                                    {% if daylog and daylog.category == "Major" %}checked{% endif %}>
                                Major
                            </label>
                        </div>
                        {% if errors.category %}
                            {% include "alert.html" with type='danger' message=errors.category %}
                        {% endif %}
                    </div>
                </div>

                {% if operation != 'view' %}
                <div class="form-group row">
                    <div class="offset-sm-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </div>
                </div>
                {% endif %}
            </div><!-- .container -->

        </form>

    </div><!-- .card-block -->

    <div class="card-footer text-center">
        <a href="/daylog" class=" btn btn-primary btn-sm">Back</a>
    </div>

</div><!-- .card -->

{% endblock %}

daylogapp/daylog/templates/daylog/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="card">
        <h3 class="card-header">Day Log</h3>

        {% if daylogs %}
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Created</th>
                    <th>Updated</th>
                    <th>Tasks</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            {% for daylog in daylogs %}
                <tr>
                    <td>
                        <a href="{% url 'daylog:details' daylog.slug %}">
                            <strong>{{ daylog.title }}</strong></td>
                        </a>
                    <td>
                        <code>{{ daylog.created_at|date:"Y-m-d" }}</a>
                        </code>
                    </td>
                    <td>
                        <code>{{ daylog.modified_at|date:"Y-m-d" }}</code>
                    </td>
                    <!-- TODO: Get number of Tasks per DayLog -->
                    <td><code>0</code></td>
                    <td>
                        <a href="{% url 'daylog:edit' daylog.slug %}" class="btn btn-primary btn-sm">Edit</a>
                    </td>
                    <td>
                        <form action="{% url 'daylog:delete' daylog.slug %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="card-block">
            <div class="alert alert-info" role="alert">
                There are no Day Logs available.
            </div>
        </div>
        {% endif %}

        <div class="card-footer text-center">
            <a href="/daylog/create" class=" btn btn-primary">Create Day Log</a>
        </div>

    </div><!-- .card -->

{% endblock %}

daylogapp/templates/alert.html
<div class="alert alert-{{ type }}" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message | striptags }}
</div>

daylogapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>DayLogApp</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>

    <body>

        <nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="margin-bottom: 2em">
            <div class="container col-sm-6">
                <button class="navbar-toggler navbar-toggler-right" type="button"
                    data-toggle="collapse" data-target="#navbar"
                    aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/">DayLogApp</a>
            </div>
        </nav>

        <div class="row">
            <div class="container col-sm-6">
            {% if messages %}
                {% for message in messages|slice:":1" %}
                    {% include "alert.html" with type=message.extra_tags  message=message %}
                {% endfor %}
            {% endif %}

            {% block content %}
            {% endblock %}

                <hr/>
                <div class="text-center">
                    <p>
                        <a target="_blank" href="https://bitbucket.org/giltroymeren/daylogapp-django">
                            BitBucket
                        </a> |
                        <a target="_blank" href="https://giltroymeren.aerobatic.io/2017/05/22/day-log-app-django-part-1/">
                            Documentation
                        </a>
                    </p>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    </body>
</html>